
trigger:
  branches:
    include:
    - main
    - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'Use Python 3.11'

- script: |
    python -m pip install --upgrade pip
    python -m pip install build twine setuptools wheel
  displayName: 'Install build tools'

- script: |
    python -m build
  displayName: 'Build package'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'Book Store Chatbot/BS_Chatbot_Feed'
  displayName: 'Authenticate to Azure Artifacts'

- script: |
    python -m twine upload -r BS_Chatbot_Feed --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Publish package'

#testing
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run pytest tests'
  
